name: Publish
on: [pull_request, push]

jobs:
  swig:
    name: Generate the SWIG wrappers
    uses:
      ./.github/workflows/swig.yml

  
  build-native:
    name: Build native ${{ matrix.platform && '' || '' }}
    needs: swig

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        enable_tiff: [true, false]

    uses:
      ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      native: true
      wasm: false
      id: native-${{ matrix.platform }}-${{ matrix.enable_tiff && 'tiff' || 'no_tiff'}}
      enable_tiff: ${{ matrix.enable_tiff }}


  build-wasm:
    name: Build WASM ${{ matrix.enable_tiff && '' || '' }}
    needs: swig

    strategy:
      fail-fast: false
      matrix:
        inline_projdb: [true, false]
        enable_tiff: [true, false]

    uses:
      ./.github/workflows/build.yml
    with:
      platform: ubuntu-latest
      native: false
      wasm: true
      enable_tiff: ${{ matrix.enable_tiff }}
      inline_projdb: ${{ matrix.inline_projdb }}
      id: wasm-${{ matrix.inline_projdb && 'inlined' || 'external' }}-${{ matrix.enable_tiff && 'tiff' || 'no_tiff'}}

